
/**
 * AUTO-GENERATED FILE @ Sun, 27 Oct 2024 14:16:33 GMT - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.1.0.8
 * $ schemats generate postgres://username:password@localhost:5433/pawpal_clinic_database -C -s public
 *
 */



export interface Commandes {
  commandeId: number
  proprietaireId: number
  dateCommande?: Date | null
  statut: string
}

export interface Avis {
  avisId: number
  rendezVousId: number
  note?: number | null
  commentaire?: string | null
  creeLe?: Date | null
}

export interface Rappels {
  rappelId: number
  animalId: number
  veterinaireId: number
  dateRappel: Date
  typeRappel?: string | null
  statut: string
  creeLe?: Date | null
}

export interface ServicesAnimaux {
  serviceAnimalId: number
  animalId: number
  veterinaireId: number
  serviceId: number
  dateService: Date
  remarques?: string | null
}

export interface Services {
  serviceId: number
  nomService: string
  description?: string | null
  prix?: number | null
}

export interface Utilisateurs {
  utilisateurId: number
  email: string
  role: string
  prenom?: string | null
  nom?: string | null
  telephone?: string | null
  creeLe?: Date | null
}

export interface CommandeProduits {
  commandeProduitId: number
  commandeId: number
  produitId: number
  quantite: number
  prix: number
}

export interface RendezVous {
  rendezVousId: number
  animalId: number
  veterinaireId: number
  dateRendezVous: Date
  statut: string
  motif?: string | null
  creeLe?: Date | null
}

export interface Produits {
  produitId: number
  nomProduit: string
  description?: string | null
  prix: number
  quantiteStock: number
  creeLe?: Date | null
}

export interface Animaux {
  animalId: number
  proprietaireId: number
  nom: string
  race?: string | null
  age?: number | null
  historiqueMedical?: string | null
  creeLe?: Date | null
}

export interface Tables {
  commandes: Commandes,
  avis: Avis,
  rappels: Rappels,
  services_animaux: ServicesAnimaux,
  services: Services,
  utilisateurs: Utilisateurs,
  commande_produits: CommandeProduits,
  rendez_vous: RendezVous,
  produits: Produits,
  animaux: Animaux
}